version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        RUBY_VERSION: 3.4.1
    volumes:
      - ..:/rails:cached
      - bundle:/usr/local/bundle
      - rails_cache:/rails/tmp/cache
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=sqlite3:/rails/db/development.sqlite3
    ports:
      - "3000:3000"
    command: sleep infinity

volumes:
  bundle:
  rails_cache: