ARG RUBY_VERSION=3.4.1
FROM ruby:${RUBY_VERSION}-slim as base

# Install development dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libvips \
    pkg-config \
    sqlite3 \
    libsqlite3-dev \
    curl \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

# Install yarn
RUN npm install -g yarn

# Configure bundler
ENV BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_BIN=/usr/local/bundle/bin \
    PATH="${BUNDLE_BIN}:${PATH}" \
    RAILS_ENV=development

WORKDIR /rails

# Install debug tools
RUN gem install \
    solargraph \
    rubocop \
    ruby-debug-ide \
    debase

# Copy application code
COPY Gemfile Gemfile.lock ./

# Install dependencies
RUN bundle install

# Copy the rest of the application
COPY . .

# Add a script to be executed every time the container starts
COPY .devcontainer/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000

# Start the main process (for regular docker run)
CMD ["rails", "server", "-b", "0.0.0.0"]