ARG RUBY_VERSION=3.4.1
FROM ruby:${RUBY_VERSION} as base

# Install bundler
RUN gem install bundler

# Set environment variables for bundler
ENV BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_BIN=/usr/local/bundle/bin \
    PATH="${BUNDLE_BIN}:${PATH}" \
    RAILS_ENV=development

WORKDIR /rails

# Install debug tools (Ruby gems)
RUN gem install \
    solargraph \
    rubocop \
    ruby-debug-ide \
    debase

# Copy application code
COPY Gemfile Gemfile.lock ./

# Install dependencies
RUN bundle install

# Copy the rest of the application
COPY . .

# Add a script to be executed every time the container starts
COPY .docker/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000

# Start the main process (for regular docker run)
CMD ["rails", "server", "-b", "0.0.0.0"]